app:
  title: Backstage

organization:
  name: Homelab

backend:
  listen:
    port: 7007
  csp:
    connect-src: ["'self'", 'http:', 'https:']
  cors:
    methods: [GET, HEAD, PATCH, POST, PUT, DELETE]
    credentials: true

techdocs:
  builder: local
  generator:
    runIn: docker
  publisher:
    type: local
