app:
  baseUrl: http://localhost:7007

backend:
  baseUrl: http://localhost:7007
  database:
    client: pg
    connection:
      host: ${POSTGRES_HOST}
      port: ${POSTGRES_PORT}
      user: ${POSTGRES_USER}
      password: ${POSTGRES_PASSWORD}

integrations:
  gitea:
    - host: ${GITEA_HOST}
      baseUrl: ${GITEA_BASE_URL}
      username: ${GITEA_USER}
      password: ${GITEA_PASSWORD}

# TODO https://backstage.io/docs/auth
auth:
